spring:
  application:
    name: student-service
  jackson:
    default-property-inclusion: non_null
    property-naming-strategy: SNAKE_CASE
  datasource:
    url: jdbc:${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  config:
    use-legacy-processing: true
jpa:
  show-sql: true
  hibernate:
    ddl-auto: create
logging:
  level:
    org:
      springframework:
        web: DEBUG
        data: DEBUG
        jpa: DEBUG
      hibernate:
        type: trace
        sql: DEBUG